contents update
nervosnetwork/godwoken-doc pull request #73
Opened 2022-09-06 12:54 UTC by ashleewang888

Commits sum up:

1st:
 - updated FAQ
 - updated integration gw-web3 Compatibility

2nd:
 - created scripts doc

3rd:
 - updated integration(EVM-compatible) doc

2022-09-07 09:05 UTC, Flouse requested changes

2022-09-07 09:05 UTC, Flouse commented on versioned_docs/version-1.5(WIP)/faq.md
> +### CKB transfer on Godwoken testnet via Metamask has failed. What is the solution?
I think this question could be removed in Godwoken v1.6+.

2022-09-07 19:54 UTC, i-am-sam-codes requested changes

2022-09-07 19:54 UTC, i-am-sam-codes commented on versioned_docs/version-1.5(WIP)/gwScripts.md
> +Further details about the Godwokende mechanism can be found at [Life of a godwoken transaction](https://github.com/nervosnetwork/godwoken/blob/develop/docs/life_of_a_godwoken_transaction.md) and [Lif
>Further details about the Godwokende mechanism can be found at 
- Godwokende --> Godwoken

2022-09-07 19:54 UTC, i-am-sam-codes commented on versioned_docs/version-1.5(WIP)/gwScripts.md
> +Rollup cell is an identity cell on CKB which stores the [GlobalState](https://github.com/nervosnetwork/godwoken/blob/develop/crates/types/schemas/godwoken.mol), a structure that represents the layer-
>Rollup cell is an identity cell on CKB which stores the 
- The Roll up cell

2022-09-07 19:54 UTC, i-am-sam-codes commented on versioned_docs/version-1.5(WIP)/gwScripts.md
> +To update the Rollup cell, we need to build a tx to consume the old cell and generate a new Rollup cell as the tx's output. We also need to provide a args in the tx's witness: `RollupAction`, which i
>And state validator 
- The state validator

2022-09-07 19:54 UTC, i-am-sam-codes commented on versioned_docs/version-1.5(WIP)/gwScripts.md
> +    - The layer-2 transactions, deposits, and withdrawals are included in a layer-2 block structure. We won't verify the signatures of txs and withdrawald on-chain since we are using the optimistic m
- withdrawald --> withdrawals or withdrawal

2022-09-07 19:54 UTC, i-am-sam-codes commented on versioned_docs/version-1.5(WIP)/gwScripts.md
> +Also, another important structure need to be mentioned here is the `RollupConfig`, where we define the consensus and initial Rollup settings in the cell.
- need to be --> needed to be

2022-09-07 19:54 UTC, i-am-sam-codes commented on versioned_docs/version-1.5(WIP)/gwScripts.md
> +The `lock` field of Rollup cell has its own rules comparatively. We assumed in the initial design that everyone who stakes can submit to the Rollup. But during the preliminary phase, we want a more s
>The `lock` field of Rollup cell
- of Rollup cell --> a Rollup cell

2022-09-07 19:54 UTC, i-am-sam-codes commented on versioned_docs/version-1.5(WIP)/gwScripts.md
> +A layer1 user can join the Rollup by creating a deposit cell. Godwoken collects deposit cells from the layer1 blockchain and puts them into the input of the tx which submits layer-2 block.
- layer1 --> layer-1
>which submits layer-2 block.
- which submits to a layer-2 block.

2022-09-07 19:54 UTC, i-am-sam-codes commented on versioned_docs/version-1.5(WIP)/gwScripts.md
> +Rollup uses the custodian lock to hold the deposited assets. `CustodianLockArgs` is the args of custodian lock, the field `deposit_block_number` represents the block number that the deposit is proces
>Rollup uses the custodian lock to hold the deposited assets. 
- Our Rollup uses the custodian lock to hold the deposited assets.

2022-09-07 19:54 UTC, i-am-sam-codes commented on versioned_docs/version-1.5(WIP)/gwScripts.md
> +For unfinalized custodian cells, once the deposit block is reverted, these cells must be also reverted to the deposit cells.
>these cells must be also reverted to the deposit cells.
- be also --> also be

2022-09-07 19:54 UTC, i-am-sam-codes commented on versioned_docs/version-1.5(WIP)/gwScripts.md
> +For finalized custodian cells, since they are finalized, we can free merge or split these cells.
- Since finalized custodian cells are finalized, we can free merge or split these cells.

2022-09-07 19:54 UTC, i-am-sam-codes commented on versioned_docs/version-1.5(WIP)/gwScripts.md
> +When a Godwoken node found that an invalid state in the Rollup, it can send a `RollupEnterChallenge` action to the Rollup cell and generate a challenging cell. A challenge cell must set a challenging
>When a Godwoken node found that an invalid state in the Rollup,
- found --> finds an invalid state in the Rollup,
- generate --> generates

2022-09-07 19:54 UTC, i-am-sam-codes commented on versioned_docs/version-1.5(WIP)/gwScripts.md
> +If the challenging unit does not get cancelled when completed, the challenger can execute the `RollupRevert` action on the Rollup cell and take stake cell sent by reverted block submitter as a reward
- take stake cell sent --> takes the stake cell sent by the reverted block

2022-09-07 19:54 UTC, i-am-sam-codes commented on versioned_docs/version-1.5(WIP)/gwScripts.md
> +Godwoken account consisted of the following fields: `(id: u32, nonce: u32, script: Script)`. The `script` field determines the script that the account used.
- account --> accounts

2022-09-07 19:54 UTC, i-am-sam-codes commented on versioned_docs/version-1.5(WIP)/gwScripts.md
> +Layer-2 scripts exist in two types: lock and contract. If an account ID appears in `l2tx.from_id`, we will assume that the account's script is a lock, implying that the script follows the lock script
- e.g. --> e.g.,

2022-09-07 19:54 UTC, i-am-sam-codes commented on versioned_docs/version-1.5(WIP)/gwScripts.md
> +ETH Account Lock is a 2-layer lock script that verifies the layer 2 account signature.
- layer 2 --> layer-2

2022-09-07 19:54 UTC, i-am-sam-codes commented on versioned_docs/version-1.5(WIP)/gwScripts.md
> +Meta contract is a layer-2 contract script. A built-in layer-2 account allows creating another account by sending a tx to the account. Meta contract args is `MetaContractArgs`, the built-in contract
-  the built-in contract id is `0`. -->  and the built-in contract id is `0`.

2022-09-07 19:54 UTC, i-am-sam-codes commented on versioned_docs/version-1.5(WIP)/gwScripts.md
> +sUDT contract is a layer-2 contract script that keeps a consistent mapping to the layer-1 sUDT. The layer-1 sUDT script hash is equal to `account.script.args`. When the user deposits a new type of sU
-  the built-in CKB Simple UDT contract id is `1`. --> and the built-in CKB Simple UDT contract id is `1`.

2022-09-07 19:54 UTC, i-am-sam-codes commented on versioned_docs/version-1.5(WIP)/gwScripts.md
> +When a user deposits token to create a new account, a corresponding Ethereum address will be inserted into the contract. If the account is created through a Meta contract, the user must register the
- token --> tokens

2022-09-07 19:54 UTC, i-am-sam-codes commented on versioned_docs/version-1.5(WIP)/gwScripts.md
> +Polyjuice backend accepts an Ethrereum-like transaction and executes it in EVM. Ethereum [transaction structure](https://eth.wiki/json-rpc/API#eth_sendtransaction) is as follows:
- in EVM --> in the EVM
- Ethereum [transaction structure] --> The Ethereum [transaction structure]

2022-09-07 19:54 UTC, i-am-sam-codes commented on versioned_docs/version-1.5(WIP)/gwScripts.md
> +In polyjuice, `from` and `to` are included in RawL2Transaction (`from_id`, `to_id`) directly. `call_kind`(CREATE/CALL), `gas`, `gasPrice`, `value` and `data` are included in `RawL2Transaction.args`.
>In polyjuice,
- With polyjuice,

2022-09-07 19:54 UTC, i-am-sam-codes commented on versioned_docs/version-1.5(WIP)/integration.md
> +pCKB serves a similar purpose for the Godwoken chain as ETH does for the Ethereum chain, in the sense that it is used for collecting transaction fees. In Ethereum, the gas for each smart contract is
>And the transaction fee is then calculated by multiplying the gas with the specified gas price.
- the gas with the --> the gas by the 

>(in wei, i.e. 10<sup>-18</sup> ETH)
- i.e. --> i.e.,

2022-09-07 19:54 UTC, i-am-sam-codes commented on versioned_docs/version-1.5(WIP)/integration.md
> +Polyjuice runs EVM on [ckb-vm](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0003-ckb-vm/0003-ckb-vm.md#risc-v-runtime-model). EVM has no limit on memory usage, yet EVM has a limit of 1024 o
>refer to [here]
- refer [here]

2022-09-07 21:48 UTC, i-am-sam-codes approved these changes
Only thing I suggest is to have a uniform set of writing when writing about layers for example: Layer 1 or Layer-1 or L1

Not different all over the article 👍

2022-09-07 22:02 UTC, ashleewang888 commented
> Only thing I suggest is to have a uniform set of writing when writing about layers for example: Layer 1 or Layer-1 or L1
> 
> Not different all over the article 👍

Got it. I will unify the writing format afterward.

2022-09-08 10:01 UTC, Flouse approved these changes

2022-09-08 10:08 UTC, merged