FAQ update
nervosnetwork/godwoken-doc pull request #81
Opened 2022-09-19 10:47 UTC by ashleewang888

- layout modified
- content updated

2022-09-26 08:25 UTC, Flouse requested changes

2022-09-26 08:25 UTC, Flouse commented on versioned_docs/version-1.6(WIP)/faq.md
> +Defi contracts often require interests to be calculated by block number. However, both v0 and v1 networks do not have a fixed layer2 block interval (it is affected by layer1 block interval).
```suggestion
DeFi contracts often require interests to be calculated by block number. However, both v0 and v1 networks do not have a fixed layer2 block interval (it is affected by layer1 block interval).
```

2022-09-26 08:25 UTC, Flouse commented on versioned_docs/version-1.6(WIP)/faq.md
> +### Failed to transfer token via Metamask on Godwoken
Support for native token transfer
Previously when using Metamask on Godwoken, it was necessary to add a custom ERC20 contract for pCKB to send pCKB tokens. This requirement is no longer required. pCKB is now treated as a native token on Godwoken and works out of the box with Metamask.

- https://github.com/nervosnetwork/godwoken-polyjuice/pull/173
- https://github.com/nervosnetwork/godwoken/pull/788
- https://github.com/nervosnetwork/godwoken-web3/pull/505

2022-09-26 08:25 UTC, Flouse commented on versioned_docs/version-1.6(WIP)/faq.md
> +Q: The average block confirmation interval on Godwoken is 30s or more, yet I would like to have my transactions completed more quickly, what should I do to make this happen?
- Avg. Block Time of Godwoken testnet_v1: https://v1.testnet.gwscan.com/
- Avg. Block Time of Godwoken mainnet_v1: https://v1.gwscan.com/

2022-09-27 14:56 UTC, ashleewang888 commented
@Flouse

2022-09-27 16:55 UTC, Flouse approved these changes

2022-09-27 16:57 UTC, merged